version: "3.2"
services:
  transmission:
    image: tundrasoft/transmission-docker:latest
    ports:
      - 9091:9091 # WebUI
      - 51413:51413 # Torrent Port TCP
      - 51413:51413/udp # Torrent Port UDP
    environment:
      - PUID=1000 # for UserID
      - PGID=1000 # for GroupID
      - TZ=Asia/Kolkata # Specify a timezone to use EG Europe/London
      - TRANSMISSION_WEB_HOME=/combustion-release/ # Specify an alternative UI options are /combustion-release/, /transmission-web-control/, and /kettu/
      # - USERNAME=username # Specify an optional username for the interface
      # - PASSWORD=password # Specify an optional password for the interface
    volumes:
      - transmission_config:/config # Where transmission should store config files and logs.
      - transmission_download:/downloads # Local path for downloads
      - transmission_watch:/watch # Watch folder for torrent files.
    networks:
      - swarm_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  swarm_network:
    external: true

volumes:
  transmission_config:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nas,nolock,soft,rw"
      device: ":/export/docker-apps/transmission/config/"

  transmission_download:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nas,nolock,soft,rw"
      device: ":/export/downloads/transmission/"

  transmission_watch:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nas,nolock,soft,rw"
      device: ":/export/docker-apps/transmission/watch/"
